### ISSUE TITLE
Application won't start

### ISSUE THREAD

**Issue by aderito7** [deonclem/angular-webpack-typescript#1]
When typing `npm start` I get the following output:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-webpack@1.0.0~prestart: angular-webpack@1.0.0
6 silly lifecycle angular-webpack@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular-webpack@1.0.0~start: angular-webpack@1.0.0
8 verbose lifecycle angular-webpack@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular-webpack@1.0.0~start: PATH: C:\Users\Me\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Me\Desktop\angular-webpack-typescript\node_modules\.bin;C:\Program Files (x86)\iis express\PHP\v5.6;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\Me\Anaconda3;C:\Users\Me\Anaconda3\Scripts;C:\Users\Me\Anaconda3\Library\bin;C:\Users\Me\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\Me\AppData\Local\Programs\Python\Python35-32\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Me\A;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\dotnet\;C:\Users\Me\Desktop\neard\bin\apache\apache2.2.22\bin;C:\Users\Me\Desktop\neard\bin\php\php5.3.13;C:\Users\Me\Desktop\neard\bin\php\php5.3.13\pear;C:\Users\Me\Desktop\neard\bin\php\php5.3.13\imagick;C:\Users\Me\Desktop\neard\bin\nodejs\nodejs4.4.5;C:\Users\Me\Desktop\neard\tools\composer\composer1.1.2;C:\Users\Me\Desktop\neard\tools\drush\drush7.3.0;C:\Users\Me\Desktop\neard\tools\git\git2.9.0\bin;C:\Users\Me\Desktop\neard\tools\imagemagick\imagemagick6.9.3-10;C:\Users\Me\Desktop\neard\tools\phpmetrics\phpmetrics1.0.1;C:\Users\Me\Desktop\neard\tools\phpunit\phpunit4.8.26;C:\Users\Me\Desktop\neard\tools\svn\svn1.7.22\bin;C:\Users\Me\Desktop\neard\tools\wpcli\wpcli0.20.4;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\Program Files (x86)\Pandoc\;C:\Program Files\nodejs\;C:\Users\Me\Anaconda3;C:\Users\Me\Anaconda3\Scripts;C:\Users\Me\Anaconda3\Library\bin;C:\Users\Me\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\Me\AppData\Local\Programs\Python\Python35-32\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\wamp\bin\php\php5.6.19;C:\Users\Me\AppData\Roaming\Composer\vendor\bin;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\MongoDB\Server\3.2\bin;C:\Users\Me\AppData\Local\Microsoft\WindowsApps;C:\Users\Me\AppData\Roaming\npm
10 verbose lifecycle angular-webpack@1.0.0~start: CWD: C:\Users\Me\Desktop\angular-webpack-typescript
11 silly lifecycle angular-webpack@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'npm install && node_modules/.bin/typings install && npm run-script dev' ]
12 silly lifecycle angular-webpack@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular-webpack@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular-webpack@1.0.0 start: `npm install && node_modules/.bin/typings install && npm run-script dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-webpack@1.0.0
16 verbose cwd C:\Users\Me\Desktop\angular-webpack-typescript
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.6.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error angular-webpack@1.0.0 start: `npm install && node_modules/.bin/typings install && npm run-script dev`
22 error Exit status 1
23 error Failed at the angular-webpack@1.0.0 start script 'npm install && node_modules/.bin/typings install && npm run-script dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-webpack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm install && node_modules/.bin/typings install && npm run-script dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-webpack
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-webpack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by deonclem** [comment]
This probably comes from the fact that you are using Windows. I can't try to do the install on a Windows machine right now, but here are a couple of leads for you to look into :

http://stackoverflow.com/questions/29916581/webpack-error-while-running-npm-start

https://github.com/angular/angular-seed/issues/199

https://github.com/angular/angular-seed/issues/292
